server:
    port: 43008

spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/job?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
#        url: jdbc:mysql://127.0.0.1:3306/similar_recruitment?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
#        url: jdbc:mysql://106.54.231.23:3306/similar_recruitment?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
        username: root
        password: root

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: job.entity
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
  
logging:
  level: 
    job.mapper: debug


